//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recommend.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Recommend.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1	Toy Story (1995)	53059
        ///2	Jumanji (1995)	22466
        ///3	Grumpier Old Men (1995)	15111
        ///4	Waiting to Exhale (1995)	2898
        ///5	Father of the Bride Part II (1995)	14323
        ///6	Heat (1995)	25275
        ///7	Sabrina (1995)	14628
        ///8	Tom and Huck (1995)	1443
        ///9	Sudden Death (1995)	4255
        ///10	GoldenEye (1995)	30429
        ///11	American President, The (1995)	18770
        ///12	Dracula: Dead and Loving It (1995)	4157
        ///13	Balto (1995)	1530
        ///14	Nixon (1995)	6607
        ///15	Cutthroat Island (1995)	2977
        ///16	Casino (1995)	18245
        ///17	Sense and Sensibility (1995)	22872
        ///18	Four Rooms (1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Movies {
            get {
                return ResourceManager.GetString("Movies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1	0	0.032
        ///1	1	0.035
        ///1	2	0.070
        ///1	3	0.114
        ///1	4	0.105
        ///1	5	0.186
        ///1	6	0.040
        ///1	7	0.208
        ///1	8	0.261
        ///1	9	0.032
        ///1	10	0.563
        ///1	11	0.067
        ///1	12	0.191
        ///1	13	0.009
        ///1	14	0.032
        ///1	15	0.355
        ///1	16	0.007
        ///1	17	0.134
        ///1	18	0.440
        ///1	19	0.209
        ///1	20	0.321
        ///1	21	0.261
        ///1	22	0.043
        ///1	23	0.015
        ///1	24	0.085
        ///1	25	0.074
        ///1	26	0.158
        ///1	27	0.062
        ///1	28	0.894
        ///1	29	0.699
        ///1	30	0.026
        ///1	31	0.204
        ///1	32	0.357
        ///1	33	0.044
        ///1	34	0.028
        ///1	35	0.303
        ///1	36	0.058
        ///1	37	0.011
        ///1	38	0.022
        ///1	39	0.014
        ///1	40	0.011
        ///1	41	0.025
        ///1	42	0.130
        ///1	43	0.044
        ///1	44	0.195
        ///1	45	0.183
        ///1	46	0.007
        ///1	47	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string tag_relevancetxt {
            get {
                return ResourceManager.GetString("tag_relevancetxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0	007	61
        ///1	007 (series)	24
        ///2	18th century	37
        ///3	1920s	42
        ///4	1930s	55
        ///5	1950s	49
        ///6	1960s	57
        ///7	1970s	71
        ///8	1980s	109
        ///9	19th century	68
        ///10	3d	122
        ///11	70mm	30
        ///12	80s	52
        ///13	9/11	31
        ///14	aardman	38
        ///15	aardman studios	13
        ///16	abortion	45
        ///17	absurd	86
        ///18	action	758
        ///19	action packed	69
        ///20	adaptation	45
        ///21	adapted from:book	142
        ///22	adapted from:comic	80
        ///23	adapted from:game	22
        ///24	addiction	103
        ///25	adolescence	59
        ///26	adoption	24
        ///27	adultery	86
        ///28	adventure	440
        ///29	affectionate	23
        ///30	afi 100	23
        ///31	afi 100 (laughs)	20
        ///32	afi 100 (m [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string tagstxt {
            get {
                return ResourceManager.GetString("tagstxt", resourceCulture);
            }
        }
    }
}
